tts:
  model_name: "tts_models/en/ljspeech/tacotron2-DDC"
  gpu: true

repository:
  voices_dir: "~/.cache/tts-server/voices"

server:
  host: "127.0.0.1"
  port: 1644
  reload: false

audio:
  device_index: null
  buffer_size: 2048
  default_sample_rate: 22050
  default_channels: 1